/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define BIT(x) (1UL << (x))
#define PIN(bank, num) (((bank - 'A') << 8) | (num))
#define PINNUM(pin) ((pin)&0xFFU)
#define PINBANK(pin) ((pin) >> 8)

struct gpio {
    volatile uint32_t MODER, OTYPER, OSPEEDR, PUPDR, IDR, ODR, BSRR, LCKR, AFRL, AFRH, BRR;
};
#define gpioCreate(bank) ((struct gpio *)(0x50000000UL + 0x400UL * (bank)))

enum {InputMode, OutputMode, AlternateFunctionMode, AnalogMode};

static inline void gpioSetMode(uint16_t pin, uint8_t mode)
{
    struct gpio *gpio = gpioCreate(PINBANK(pin));
    uint8_t num = PINNUM(pin);
    gpio->MODER &= ~(3UL << (num * 2U));
    gpio->MODER |= ((uint32_t)(mode & 3U) << (num * 2U));
}

static inline void gpioSetAF(uint16_t pin, uint8_t af_num)
{
    struct gpio *gpio = gpioCreate(PINBANK(pin));
    uint8_t num = PINNUM(pin);
    if (num < 8U) {
        gpio->AFRL &= ~(0xFUL << (num * 4U));
        gpio->AFRL |= ((uint32_t)(af_num & 0xFU) << (num * 4U));
    } else {
        gpio->AFRH &= ~(0xFUL << ((num - 8U) * 4U));
        gpio->AFRH |= ((uint32_t)(af_num & 0xFU) << ((num - 8U) * 4U));
    }
}

struct rcc {
    volatile uint32_t CR, ICSCR, CFGR, PLLCFGR, RESERVED0, CRRCR, CIER, CIFR, CICR, IOPRSTR, AHBRSTR,
        APBRSTR1, APBRSTR2, IOPENR, AHBENR, APBENR1, APBENR2, IOPSMENR, AHBSMENR, APBSMENR1, APBSMENR2,
        CCIPR, CCIPR2, BDCR, CSR;
};
#define RCC ((struct rcc *) (0x40021000))

struct dma_channel {
    volatile uint32_t CCR, CNDTR, CPAR, CMAR;
};
struct dma {
    volatile uint32_t ISR, IFCR;
    struct dma_channel channel[7];
};
#define DMA1 ((struct dma *) (0x40020000))

struct dmamux {
    volatile uint32_t CXCR[11];
};
#define DMAMUX1 ((struct dmamux *) (0x40020800))

struct tim {
    volatile uint32_t CR1, CR2, SMCR, DIER, SR, EGR, CCMR1, CCMR2, CCER, CNT, PSC, ARR;
};
#define TIM2 ((struct tim *) (0x40000000))

struct usart {
    volatile uint32_t CR1, CR2, CR3, BRR, GTPR, RTOR, RQR, ISR, ICR, RDR, TDR;
};
#define USART2 ((struct usart *) (0x40004400))

struct adc {
    volatile uint32_t ISR, IER, CR, CFGR1, CFGR2, SMPR, RESERVED0, RESERVED1, AWD1TR, AWD2TR, CHSELR,
        AWD3TR, RESERVED2, RESERVED3, RESERVED4, RESERVED5, DR, RES[23], AWD2CR, AWD3CR, R[3], CALFACT,
        RE[148];
};
#define ADC ((struct adc *) (0x40012400))

#define ADC_CFGR1_DMAEN BIT(0)
#define ADC_CFGR1_DMACFG BIT(1)
#define ADC_CFGR1_EXTSEL_Msk (0x7 << 6)
#define ADC_CFGR1_EXTSEL_TIM2_TRGO (0x2 << 6)
#define ADC_CFGR1_EXTEN_Msk (0x3 << 10)
#define ADC_CFGR1_EXTEN_RISING BIT(10)
#define ADC_CFGR1_CONT BIT(13)

#define ADC_CR_ADEN BIT(0)
#define ADC_CR_ADSTART BIT(2)
#define ADC_CR_ADCAL BIT(31)

#define NVIC_ISER0 (*(volatile uint32_t *) (0xE000E100))

#define BUFFER_SIZE 200
volatile uint16_t adc_dma_result[BUFFER_SIZE];

static uint16_t uart_tx_snapshot[BUFFER_SIZE];
volatile bool uart_block_ready = false;

#define HEADER1 0xF1
#define HEADER2 0xF1

#define STK_CSR (*(volatile uint32_t *) (0xE000E010))
#define STK_RVR (*(volatile uint32_t *) (0xE000E014))
#define STK_CVR (*(volatile uint32_t *) (0xE000E018))
volatile uint32_t msTicks = 0;

void SysTick_Handler(void)
{
    msTicks++;
}

void systick_init(uint32_t ticks)
{
    STK_RVR = ticks - 1U;
    STK_CVR = 0U;
    STK_CSR = 7U;
}

void DMA1_Channel1_IRQHandler(void)
{
    uint32_t isr = DMA1->ISR;
    if (isr & BIT(1)) {
        DMA1->IFCR = BIT(1);
        for (uint32_t i = 0U; i < BUFFER_SIZE; i++) {
            uart_tx_snapshot[i] = adc_dma_result[i];
        }
        uart_block_ready = true;
    }
}

static inline void uart_write_char(char c)
{
    while ((USART2->ISR & BIT(7)) == 0U) {
        __asm volatile("nop");
    }
    USART2->TDR = (uint32_t)(uint8_t)c;
}

static void uart_write_bytes(const uint8_t *p, uint32_t len)
{
    for (uint32_t i = 0U; i < len; i++) {
        uart_write_char((char)p[i]);
    }
}

static inline void delay(uint32_t ms)
{
    uint32_t t0 = msTicks;
    while ((msTicks - t0) < ms) {
        __asm volatile("nop");
    }
}

int main(void)
{
    __asm volatile("cpsie i");
    systick_init(16000U);

    RCC->IOPENR |= BIT(0);

    uint16_t analog_pa0 = PIN('A', 0);
    gpioSetMode(analog_pa0, AnalogMode);

    uint16_t uart_tx = PIN('A', 2);
    gpioSetMode(uart_tx, AlternateFunctionMode);
    gpioSetAF(uart_tx, 1U);

    uint16_t digital_lodminus = PIN('A', 9);
    gpioSetMode(digital_lodminus, InputMode);
    uint16_t digital_lodplus = PIN('A', 8);
    gpioSetMode(digital_lodplus, InputMode);

    struct gpio *gpioA = gpioCreate(PINBANK(digital_lodminus));

    RCC->APBENR1 |= BIT(17);
    USART2->BRR = 139U;
    USART2->CR1 |= BIT(3) | BIT(0);

    RCC->APBENR1 |= BIT(0);
    TIM2->PSC = 0U;
    TIM2->ARR = 15999U;
    TIM2->EGR = BIT(0);
    TIM2->CR2 = (2U << 4);

    RCC->APBENR2 |= BIT(20);
    RCC->AHBENR |= BIT(0);

    DMA1->channel[0].CPAR = (uint32_t)&(ADC->DR);
    DMA1->channel[0].CMAR = (uint32_t)adc_dma_result;
    DMA1->channel[0].CNDTR = BUFFER_SIZE;
    DMA1->channel[0].CCR = BIT(0) | BIT(1) | BIT(5) | BIT(7) | BIT(8) | BIT(10);
    DMAMUX1->CXCR[0] = 5U;

    NVIC_ISER0 = (1UL << 9U);

    ADC->CR |= BIT(28);
    delay(1U);
    ADC->CR |= ADC_CR_ADCAL;
    while (ADC->CR & ADC_CR_ADCAL) {
        __asm volatile("nop");
    }

    ADC->CFGR1 = (ADC->CFGR1 & ~(ADC_CFGR1_CONT | ADC_CFGR1_EXTSEL_Msk | ADC_CFGR1_EXTEN_Msk)) |
                 (ADC_CFGR1_DMAEN | ADC_CFGR1_DMACFG | ADC_CFGR1_EXTSEL_TIM2_TRGO | ADC_CFGR1_EXTEN_RISING);

    ADC->ISR |= BIT(0);
    ADC->CR |= ADC_CR_ADEN;
    while ((ADC->ISR & BIT(0)) == 0U) {
        __asm volatile("nop");
    }

    ADC->CHSELR = BIT(0);
    while ((ADC->ISR & BIT(13)) == 0U) {
        __asm volatile("nop");
    }

    ADC->CR |= ADC_CR_ADSTART;
    TIM2->CR1 |= BIT(0);

    for (;;) {
        bool send = false;
        __asm volatile("cpsid i");
        if (uart_block_ready) {
            uart_block_ready = false;
            send = true;
        }
        __asm volatile("cpsie i");

        if (send) {
        	uint8_t lodminus_state = (gpioA->IDR & BIT(9)) ? 1 : 0;
        	uint8_t lodplus_state = (gpioA->IDR & BIT(8)) ? 1 : 0;
            uint8_t pack[6];
            pack[0] = HEADER1;
            pack[1] = HEADER2;
            pack[2] = (uint8_t)(BUFFER_SIZE & 0xFF);
            pack[3] = (uint8_t)((BUFFER_SIZE >> 8) & 0xFF);
            pack[4] = lodplus_state;
            pack[5] = lodminus_state;
            uart_write_bytes(pack, 6);
            uart_write_bytes((const uint8_t *) uart_tx_snapshot, BUFFER_SIZE * sizeof(uint16_t));
        }
    }
}
